#!/usr/bin/env python3
#
# kcri.qaap.shims.versions - generated by update-deps.sh.
# Used by the shims to report their backend version.
#
DEPS_VERSIONS = dict()
DEPS_VERSIONS["alga"] = "1.0.3-3-g949e"
DEPS_VERSIONS["fastp"] = "v0.23.2-4-g1bc2"
DEPS_VERSIONS["fastq-utils"] = "1.3.0"
DEPS_VERSIONS["flye"] = "2.9.1"
DEPS_VERSIONS["kneaddata"] = "0.10.0-21-g16fe"
DEPS_VERSIONS["multiqc"] = "v1.12-92-g888d"
DEPS_VERSIONS["picoline"] = "1.4.2"
DEPS_VERSIONS["skesa"] = "skesa.2.4.0_saute.1.3.0_2"
DEPS_VERSIONS["trim-galore"] = "0.6.7-9-g55fc"
DEPS_VERSIONS["unicycler"] = "v0.5.0-2-g96ffe"
DEPS_VERSIONS["unfasta"] = "1.3.0-3-g9418"
DEPS_VERSIONS["fastqc"] = "0.11.9"
DEPS_VERSIONS["fastq-screen"] = "0.15.2"
DEPS_VERSIONS["interop"] = "1.1.25"
DEPS_VERSIONS["ncbi-blast"] = "2.13.0"
DEPS_VERSIONS["quast"] = "5.2.0"
DEPS_VERSIONS["spades"] = "3.15.5"
DEPS_VERSIONS["trimmomatic"] = "0.39"
