#!/usr/bin/env python3
#
# kcri.qaap.shims.versions - generated by update-deps.sh.
# Used by the shims to report their backend version.
#
DEPS_VERSIONS = dict()
DEPS_VERSIONS["fastq-utils"] = "1.2.0"
DEPS_VERSIONS["kneaddata"] = "0.10.0-7-gc721"
DEPS_VERSIONS["multiqc"] = "v1.11-6-gd6d1"
DEPS_VERSIONS["picoline"] = "1.3.1"
DEPS_VERSIONS["skesa"] = "skesa.2.4.0_saute.1.3.0"
DEPS_VERSIONS["trim-galore"] = "0.6.6"
DEPS_VERSIONS["unicycler"] = "v0.4.9"
DEPS_VERSIONS["unfasta"] = "1.2.0"
DEPS_VERSIONS["fastqc"] = "0.11.9"
DEPS_VERSIONS["fastq-screen"] = "0.14.1"
DEPS_VERSIONS["interop"] = "1.1.23"
DEPS_VERSIONS["ncbi-blast"] = "2.12.0"
DEPS_VERSIONS["pilon"] = "1.24"
DEPS_VERSIONS["quast"] = "5.1.0rc1"
DEPS_VERSIONS["spades"] = "3.15.2"
DEPS_VERSIONS["spades-uni"] = "3.13.0"
DEPS_VERSIONS["trimmomatic"] = "0.39"
