#!/usr/bin/env python3
#
# kcri.qaap.shims.versions - generated by update-deps.sh.
# Used by the shims to report their backend version.
#
DEPS_VERSIONS = dict()
DEPS_VERSIONS["picoline"] = "1.1.0"
DEPS_VERSIONS["fastq-utils"] = "1.2.0"
DEPS_VERSIONS["skesa"] = "skesa.2.4.0_saute.1.3.0"
DEPS_VERSIONS["unicycler"] = "v0.4.9"
DEPS_VERSIONS["unfasta"] = "1.2.0"
DEPS_VERSIONS["kneaddata"] = "0.10.0-4-gf857"
DEPS_VERSIONS["fastqc"] = "0.11.9"
DEPS_VERSIONS["trimmomatic"] = "0.39"
DEPS_VERSIONS["ncbi-blast"] = "2.11.0"
DEPS_VERSIONS["quast"] = "5.1.0rc1"
DEPS_VERSIONS["spades"] = "3.15.2"
DEPS_VERSIONS["spades-uni"] = "3.13.0"
